ReddyLab/cegs-portal

cegs_portal/search/templates/search/v1/reg_effect.html
Fixes a that passed in the sources to the partial as the wrong variable name Also changes the header; not all sources are DHSs (some are cCREs)
Fixes https://github.com/ReddyLab/cegs-portal/issues/10
=> Show RegEffectObservation sources in REO page

cegs_portal/search/templates/search/v1/partials/_features.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/views/v1/search.py
Previously, a search URL like http://127.0.0.1:8000/search/results/?query=chr1:157909847-157959940%20hg19&facet=11 ignored the selected facet in the query.
The changes mean that a user can go to a search URL with a facet and get the expected results.
Additionally, the result table has been updated to be in line with the feature table output in tables.js This will avoid visual "popping" as one table gets replaced with another.
Fixes #15
=> Check facet boxes in and search using search query facets

cegs_portal/search/templates/search/v1/search_results.html
The pagination URL assumed an assembly had been specified. When it hadn't "None" was passed as the assembly, which broke queries.
Fixes #13
=> Fix pagination when no assembly specified

.gitlab-ci.yml
The scan and deleteimage CI steps were failing on non-main, non-prod branches.
=> Fixes "scan" and "deleteimage" CI steps

cegs_portal/search/views/v1/tests/test_reg_effects.py
Only testing the search/regeffect endpoint as search/regeffect/search
will likely be changing a lot soon.
This endpoint is very basic, so the tests can be pretty simple!
=> Reg effect url tests

cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/experiment.py, cegs_portal/search/json_templates/v1/tests/test_experiment.py, cegs_portal/search/views/v1/tests/test_experiment.py
The experiment list is always paginated, so the JSON needs to include that information so clients know how to get all the experiments.
=> Adds pagination info to experiment list JSON

cegs_portal/search/templates/search/v1/dna_features.html
* adds superfluous "chr" to a fetch url, resulting in a chromosome fetch of "chrchr1/xxxxxx/yyyyy", which doesn't exist of course
* wraps STATE_LOCATION in [], indicating that the key should be the value of STATE_LOCATION, not the string STATE_LOCATION.
=> Fixes a couple of issue with the JS on the featureloc page

cegs_portal/search/models/reg_effects.py
We need to know the facets to get the "Direction" facet_value for REOs. And any time we use "with_facet_values" we wan't to know the Direction.
This saves us an n+1 query for facets.
=> Prefetch facets when using "with_facet_values"

cegs_portal/search/models/__init__.py, cegs_portal/search/models/signals.py, cegs_portal/tasks/conftest.py, cegs_portal/tasks/tests/test_tasks.py, cegs_portal/utils/decorators.py, config/settings/base.py, config/settings/test.py
Updating the access controls for a set of dnafeatures/reos when an experiment is set private or archived can take a few moments. To avoid locking the whole server up the work should be done in the background.
There's some code in here for testing -- we don't want the new signal handler going off during tests, so I added a way to disable it.
=> Update dnafeature/reo access controls on background thread

cegs_portal/search/static/search/js/exp_viz/chromosomeSvg.js, cegs_portal/search/templates/search/v1/experiment.html
Opens a new window/tab to a search of the location of a zoomed-in bucket when it's clicked on. Also adds a different method of zooming out (clicking anywhere in the SVG area _except_ a bucket), in case the user doesn't want to open a search window.
=> Open new search window when clicking on a zoomed-in bucket

cegs_portal/search/models/__init__.py, cegs_portal/search/models/utils.py, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/search/view_models/v1/search.py, cegs_portal/search/views/custom_views.py, cegs_portal/search/views/v1/dna_features.py, cegs_portal/search/views/v1/search.py, cegs_portal/search/views/v1/tests/test_search.py, cegs_portal/utils/http_exceptions.py, cegs_portal/utils/http_responses.py
If a user does a search on a single DNA Feature, it makes sense to jump straight to that feature, rather than show an intermediate search interface. 
This is done via a redirect (HTTP status 303).
Because users can add an assembly/ref genome to the search query I added the same ability to a dnafeature id search.
QueryToken and IdType were combined because they contain the same information and need to stay in sync, so they may as well be the same Enum.
Three new tests were added to check that redirects work. Updated the old tests to search for two features so that the redirects aren't triggered.
=> Redirect search of a single feature id to the feature page

cegs_portal/tasks/conftest.py, cegs_portal/tasks/factories.py, cegs_portal/tasks/json_templates/v1/__init__.py, cegs_portal/tasks/json_templates/v1/task.py, cegs_portal/tasks/json_templates/v1/tests/test_task.py, cegs_portal/tasks/templates/tasks/v1/task_status.html, cegs_portal/tasks/tests/test_tasks.py, cegs_portal/tasks/urls.py, cegs_portal/tasks/view_models.py, cegs_portal/tasks/views.py, config/urls.py
This endpoint will be part of the response of other endpoints that create long-running/asynchronous tasks, like the upcoming experiment data request endpoint.
I don't think that tasks being available to any logged in user is a security issue, so that's the level of security were offering around this endpoint.
=> Adds task endpoint for viewing tasks

cegs_portal/tasks/views.py
Previously anyone who was logged in could see all the tasks. This modifies the permission check to only allow portal admins to see the tasks.
We'll add back some permissions as needed -- there are cases where we want non-admins to see tasks. But there's no need to let users see tasks they didn't start.
=> Improve test for who can view tasks

cegs_portal/search/static/search/js/downloadStatusWorker.js, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/views/v1/experiment.py
A new widget has been added to the experiment page. This allows users to upload a .bed file and get back data from the experiment associated with the regions defined in the .bed file.
=> Add UI to experiment page for downloading data

cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/views/v1/experiment_coverage.py, cegs_portal/static/css/project.css, extensions/exp_viz/Cargo.lock, extensions/exp_viz/Cargo.toml, extensions/exp_viz/src/filter.rs, extensions/exp_viz/src/filter_data_structures.rs, extensions/exp_viz/src/merge.rs
The experiment coverage visualization now includes a count for the number of REOs, sources, and targets currently included in the visualization.
=> Show reo,target,source counts in experiment coverage

cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/experiment.py, cegs_portal/search/json_templates/v1/tests/test_experiment.py, cegs_portal/search/models/experiment.py, cegs_portal/search/static/search/js/dom.js, cegs_portal/search/static/search/js/experiment_list/download_data.js, cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/view_models/v1/experiment.py, cegs_portal/search/views/v1/experiment.py, cegs_portal/search/views/v1/tests/test_experiment.py, cegs_portal/static/css/project.css, utils/experiment.py
Adds the ability to filter the experiment list by discrete facet. Experiments don't currently have any continuous facets so that's not implemented.
The experiment page is no longer paginated, because (hopefully) facet filtering removes the need to do so.
The experiment data loading script has been updated to add facets to experiments.
Javascript on the experiment loading page has been moved into separate files, which makes editing/formatting/sharing easier.
Tests have been updated to remove pagination stuff and take into account facet filtering.
=> Filter experiment list by discrete facet

cegs_portal/search/templates/search/index.html, cegs_portal/static/css/project.css, cegs_portal/templates/base.html
This improves the design of the landing page quite a bit. It also adds a link back to the Duke CCGR page and removes the date from the copyright notice.
=> Landing page design changes

cegs_portal/search/conftest.py, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/view_models/v1/search.py, cegs_portal/search/views/v1/search.py, cegs_portal/search/views/v1/tests/test_search.py, cegs_portal/static/css/project.css
If no assembly is specified, GRCh38 will be used. Since this is no longer explicit in the search, it has been added to the search results page so users know what assembly they are looking at results from.
=> Sets a default assembly for search

cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/views/v1/search.py
Allows the use of commas and spaces around the hyphen in chromosome location search queries. Also shows commas in the location on the search results page for better readability.
=> Allow commas in chromo location search

cegs_portal/search/models/tests/dna_feature_factory.py, cegs_portal/search/views/v1/dna_features.py
The previous test only checked the first returned result to see if a tab should be shown. This could result in a tab not being shown even if it should be. For example, if the first result had no children but the second result did then no "Children" tab would be shown.
The new tests check all returned results so this doesn't happen.
=> Improve the DNA Feature tab tests

cegs_portal/hide_admin/LICENSE, cegs_portal/hide_admin/README.md, cegs_portal/hide_admin/admin_site.py, cegs_portal/hide_admin/apps.py, cegs_portal/templates/pages/about.html, config/settings/base.py
This makes the admin site unavailable to non-admins. It also changes the default location. It's basically "in-lining" the [django-hide-admin](https://github.com/catcombo/django-hide-admin/) package.
=> Hides the admin site from prying eyes

scripts/data_generation/DCPEXPR00000002_dhs_bed_klann_2021_scceres.sh, scripts/data_generation/gen_experiment_coverage_viz.sh, scripts/data_generation/qc_plots/gen_qc_plots.sh, scripts/data_loading/load_all.sh, scripts/data_loading/load_facets.sh, scripts/data_loading/load_gencode_gff3_data.sh, scripts/data_loading/load_screen_ccres.sh
"#!/bin/bash" doesn't work in windows WSL2 terminals, as bash is at /usr/bin/bash. #!/usr/bin/env bash should work and make the scripts more universal.
=> Update script shebang lines to work on more systems

compose/local/django/Dockerfile, compose/local/django/start_hugo, compose/production/django/Dockerfile, compose/production/django/start_hugo, config/settings/base.py, requirements/base.txt
Because we want more robust task management and we want task scheduling (like "do X once a week") we need a real task queue rather than the hacked-together system we have now.
Adding huey and its configuration to the project is the first step in replacing the old tasks with new ones.
=> Add the huey task queue to the project

cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templatetags/custom_helpers.py
Added django templatetags directory to create custom_helpers to apply throughout the application. The django "filter" or "helper method"(rails) that was added is used to remove underscores from dna_feature subtype and any other text.
=> Removes underscores from dna feature subtype

cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/static/search/js/test/test_genoverse_standin.py
Changing the values of DNAFeatureType broke the genoverse browser because we were passing the URL query values directly in to the DNAFeatureType constructor.
=> Fixes genoverse and genoverse tests

config/settings/base.py, config/urls.py
This upload functionality isn't used and may even be a security problem so for now we're disabling it.
=> Disable the upload app

cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/view_models/v1/__init__.py, cegs_portal/search/view_models/v1/experiment.py, cegs_portal/search/view_models/v1/experiment_coverage.py, cegs_portal/search/views/v1/experiment_coverage.py, cegs_portal/search/views/v1/tests/test_experiment_coverage.py, scripts/data_generation/gen_experiment_coverage_viz.sh
An experiment may have multiple analyses associated with it. Each analysis should have its own coverage map because the numbers involved can change.
These changes change the code to support per-analysis coverage maps.
=> Use analysis accession for expr cov data

cegs_portal/users/views.py
We've been dinged by security twice for allowing username enumeration. We don't think this is actually a big deal because you have to be logged in to do and we basically trust all our user, but this fixes it anyway.
Now we can stop being dinged!
=> Remove username enumeration

compose/production/django/start, config/settings/base.py
STORAGES should now be used instead of STATICFILES_STORAGE, which is deprecated.
collectstatic chokes on the .bin files used for the experiment coverage. The .bin files aren't ever transmitted to the client anyway, so they should be left out of the collectstatic process.
=> Update storages and speed up collectstatic

cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/views/v1/experiment_coverage.py, compose/production/django/start, scripts/data_generation/qc_plots/gen_qc_plots.sh
plot data now has the extension .pd. experiment coverage data now has the extension .ecd.
This is mainly so "manage.py collecstatic" can be set up to ignore .ecd files that it doesn't need to do anything with but are VERY slow to process.
=> Change plot data and experiment cov data extensions

cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/views/v1/experiment_coverage.py, compose/production/django/start, config/settings/base.py, scripts/data_generation/qc_plots/gen_qc_plots.sh
plot data now has the extension .pd. experiment coverage data
now has the extension .ecd.
This is mainly so "manage.py collecstatic" can be set up to ignore .ecd
files that it doesn't need to do anything with but are VERY slow to process.
=> Change plot data and experiment cov data extensions 

cegs_portal/search/json_templates/v1/dna_features.py, cegs_portal/search/json_templates/v1/tests/test_dna_features.py, cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/static/search/js/test/test_genoverse_standin.py
The menu wasn't showing up due to changes in capitalization *d'oh* but also, since transcripts were all compacted some other changes needed to made.
=> Fix genoverse menu for transcripts/genes

cegs_portal/search/static/search/js/tables.js
The Javascript version of the significant REO table on the search results page didn't link to the experiment, it just showed the accession ID.
These changes add a link, which matches the behavior for the non-js table.
=> Link to the experiment from JS Sig REO table

cegs_portal/search/static/search/js/genoverse.js
The gene strand indicator was doing something complicated, but the strand is either "+" or "-" so it doesn't need to be.
Changes the logic on line 317 so the display is correct.
Unfortunately a bunch of formatting stuff also happened, but that's not what this PR is about.
=> Fixes genoverse gene strand indicator

cegs_portal/get_expr_data/conftest.py, cegs_portal/get_expr_data/tests.py, cegs_portal/get_expr_data/view_models.py, cegs_portal/get_expr_data/views.py, cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/search_results.py, cegs_portal/search/json_templates/v1/tests/test_search_results.py, cegs_portal/search/models/tests/dna_feature_factory.py, cegs_portal/search/static/search/js/tables.js, cegs_portal/search/templates/search/v1/partials/_sig_reg_effects.html, cegs_portal/search/views/v1/search.py, cegs_portal/search/views/v1/tests/test_search.py
Each source location is now a link to the source page. Each gene name is a link to said gene. To get to the actual REO the Effect Size, Significance, and Raw p-value are now links to the REO page.
=> Update links in sig_reo table

cegs_portal/get_expr_data/conftest.py, cegs_portal/get_expr_data/tests.py, cegs_portal/get_expr_data/urls.py, cegs_portal/get_expr_data/views.py, cegs_portal/search/templates/search/v1/partials/_sig_reg_effects.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/urls.py, cegs_portal/search/views/v1/__init__.py, cegs_portal/search/views/v1/search.py, cegs_portal/search/views/v1/tests/conftest.py, cegs_portal/search/views/v1/tests/test_search.py, setup.cfg
Instead of using awkward JS, the updates happen via HTMX. With this it made sense to move the endpoint from the get_expr_data app to the search app.
Tests also had to move, and we removed the json template since it wasn't really necessary anymore.
=> Replace sig reg effect JS with HTMX

cegs_portal/search/static/search/js/tables.js
Until we apply htmx to all tables, we will use the js row click for now. Removed accession id to follow uniformity among tables and to open more space
=> Fixed table overflow and added row click

cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/static/search/js/tables.js, cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html, cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html, cegs_portal/search/templates/search/v1/partials/_sig_reg_effects_table.html, cegs_portal/search/templates/search/v1/reg_effect.html
If the values are displayed in exponential format (because it's small) only show two decimal places. Otherwise generally use 6 fixed decimal places.
=> Modify decimal number displays

cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/search/view_models/v1/search.py, cegs_portal/search/views/v1/tests/test_feature_counts.py
* No non-assayed elements
* Distinguish between elements with significant and non-significant observations
* Change "Regulatory Effects Sources" to "Experimentally Tested Elements"
* Squishable Elements view (the gene view shouldn't need squishing)
* Fixes an n+1 query issue
=> Genoverse improvements on search results page

cegs_portal/search/json_templates/v1/feature_reg_effects.py, cegs_portal/search/json_templates/v1/tests/test_feature_reg_effects.py, cegs_portal/search/static/search/js/tables.js, cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
Targeting REO tables now have information about the type and location of the sources of the REO. They also have explicit links to the REO that don't show the REO accession ID.
=> Removes reoaccession, adds source loc info

cegs_portal/search/templates/search/v1/dna_feature.html
When a dna_feature displays all tabs, the tab bar length can overflow beyond the container.
=> Fixed tab_bar overflow

cegs_portal/search/static/search/js/exp_viz/exp_viz.js
When no experiment coverage data is found the UI is modified so the user knows that it's probably on purpose.
=> Adds UI for when no exp. coverage found

compose/production/django/start_huey
Huey deployment also needs to collectstatic to run
=> Collectstatic for huey install

cegs_portal/search/static/search/js/exp_viz/downloads.js, cegs_portal/search/static/search/js/experiment_list/download_data.js, cegs_portal/search/static/search/js/experiment_list/drag_drop.js, cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/templates/search/v1/experiment_list.html
Instead of experiments on the experiment list page being implicitly selected just by existing a user must explicitly select them.
Users can do this two ways: drag the experiment on to the selection area or click the "plus" on the experiment.
Experiments can be removed from the selection area by clicking the "X"
Users cannot download data unless at least one experiment is selected.
=> Add new methods for selecting experiments

cegs_portal/search/static/search/js/experiment_list/drag_drop.js, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/experiments.html, cegs_portal/search/urls.py, cegs_portal/search/view_models/v1/experiment.py, cegs_portal/search/views/custom_views.py, cegs_portal/search/views/v1/__init__.py, cegs_portal/search/views/v1/experiment.py, cegs_portal/search/views/v1/tests/test_experiments.py
Currently this page does nothing but show some experiment names.
This adds a link to the experiment list page, behind a feature flag, to go to the new experiments page. The link only shows when there is at least one selected experiment.
The new experiment page includes validation and authentication so users can't see experiments they aren't meant to nor can they pass arbitrary strings to the database.
To enable the waffle feature flag from the terminal:
python manager.py waffle_switch --create multi_expr_page on
To disable the flag:
python manager.py waffle_switch multi_expr_page off
To delete the flag:
python manager.py waffle_delete --switches multi_expr_page
=> Adds basic "multi-experiment analysis page"

cegs_portal/search/views/v1/tests/test_search.py
Ran pytest after a few merges and received a few errors. the load custom helpers tag created 2 additional empty lines and they needed to be accounted for on the test_search.py test. The empty lines should resolve the error.
=> pytest test_search solution

cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/templates/search/v1/experiments.html, cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html, cegs_portal/users/templates/users/downloads.html
The global "container" class should always be used instead.
=> Remove all use of "content-container" class

cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
Table header tag was open. The header name was not being displayed in proximal regulatory effects table.
=> Fixed open tag error

cegs_portal/search/tsv_templates/v1/non_targeting_reos.py
The UCSC genome browser does not recognize the headers in the file, only the data. Previously you would have to copy and paste the contents to work. Now that the headers are removed, the user can now upload the file.
=> Upload compatible bed file format

Makefile, cegs_portal/search/json_templates/v1/combined_experiments.py, cegs_portal/search/models/tests/experiment_factory.py, cegs_portal/search/static/search/js/exp_viz/combo_viz.js, cegs_portal/search/static/search/js/exp_viz/consts.js, cegs_portal/search/static/search/js/exp_viz/covTypeUtils.js, cegs_portal/search/static/search/js/exp_viz/coverageData.js, cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/static/search/js/exp_viz/highlightRegions.js, cegs_portal/search/static/search/js/exp_viz/render.js, cegs_portal/search/static/search/js/exp_viz/ui.js, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/templates/search/v1/experiments.html, cegs_portal/search/urls.py, cegs_portal/search/view_models/v1/experiment_coverage.py, cegs_portal/search/views/v1/__init__.py, cegs_portal/search/views/v1/experiment.py, cegs_portal/search/views/v1/experiment_coverage.py, compose/local/django/Dockerfile, compose/production/django/Dockerfile, extensions/exp_viz/Cargo.lock, extensions/exp_viz/Cargo.toml, extensions/exp_viz/src/filter.rs, extensions/exp_viz/src/filter_data_structures.rs, extensions/exp_viz/src/intersect_data_structures.rs, extensions/exp_viz/src/intersects.rs, extensions/exp_viz/src/lib.rs, extensions/exp_viz/src/load.rs
Combines and displays experiment coverage in a way similar to a single experiment. This includes the same ability to filter on facets.
A new kind of file has to be generated that includes data on the features each experiment has, so be sure to re-run `./scripts/data_generation/gen_experiment_coverage_viz.sh` after this gets merged into main.
The new visualization is, under the covers, different than that of the single experiment page. There is a lot of overlap though, so a lot of code was factored out to be shared between the two.
=> Show combined coverage data

cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html, cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html, cegs_portal/search/templates/search/v1/partials/_sig_reg_effects_table.html, cegs_portal/search/templates/search/v1/reg_effect.html, cegs_portal/search/templatetags/custom_helpers.py, cegs_portal/search/tsv_templates/v1/non_targeting_reos.py, cegs_portal/search/tsv_templates/v1/reg_effects.py, cegs_portal/search/views/v1/tests/test_search.py
Alex suggested that effect sizes only need 3 digits after the decimal and anything smaller should be 0 (shown as 0.000 in this implementation)
=> Format effect sizes differently

scripts/data_loading/load_all.sh
This experiment has been superceded by DCPEXPR0000000004-6.
=> Remove DCPEXPR00000001 from being loaded

config/settings/production.py, config/settings/qa.py
We're going to try using Duke's splunk instance to monitor logs. For this to work we have to send logs to the container's stdout/stderr instead of logging to disk. we also have to make sure everything relevant gets logged.
Additionally, we don't need django to mail us. We'll set up alerts in splunk.
Django logging info:
https://docs.djangoproject.com/en/4.2/topics/logging/
https://docs.djangoproject.com/en/4.2/howto/logging/
https://docs.djangoproject.com/en/4.2/ref/logging/
=> Modify logging levels

scripts/data_loading/__init__.py, scripts/data_loading/load_all.sh, scripts/data_loading/load_gencode_gff3_data.py
Speeds up gencode data loading by about 5x. This is because it uses the PostgreSQL COPY command (via psycopg2)
instead of the Django ORM to load the data. Instead of creating a lot of objects and bulk loading them the object data is
put into a StringIO object and loaded via copy_from which uses the PostgreSQL COPY under the hood.
See:
https://www.psycopg.org/docs/cursor.html#cursor.copy_from
https://www.postgresql.org/docs/current/sql-copy.html
=> Speed up genocode data loading

scripts/data_generation/ccre_bed.py, scripts/data_generation/ccre_overlaps.sh, scripts/data_generation/gen_experiment_coverage_viz.sh, scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_data.sh, scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_experiment.py, scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_data.sh, scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_experiment.py, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_analysis.py, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_experiment.py, scripts/data_loading/DCPEXPR0000000005_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000006_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022.sh, scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022_experiment.py, scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_experiment.py, scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPRa_2022.sh, scripts/data_loading/DCPEXPR0000000009_load_mccutcheon_scCERES_cd8_CRISPRi_2022.sh, utils/ccres.py
This makes two changes to associating cCREs with tested elements.
1) Generates the list of cCREs anew for each data load. Before we used same list from SCREEN every time and so weren't finding associations with "artificial" cCREs generated from previous data loads.
2) Changes how gRNA-based experiment look up/create cCREs. The initial cCRE/Tested Element overlap list is generated using the gRNAs but when creating "artificial" cCREs we use the location of the DHS the gRNA is associated with instead of the gRNA location.
=> Adjusts how associated cCREs are calculated

cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/dna_features.py, cegs_portal/search/json_templates/v1/tests/test_dna_features.py, cegs_portal/search/models/tests/dna_feature_factory.py, cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/static/search/js/test/test_genoverse_standin.py, cegs_portal/search/view_models/v1/dna_features.py
The query run when genoverse requests source features wasn't specific enough and returned too many results. Additionally the feature returned had too much information.
The first issue is being tackled by making more specific query properties. The second by not requesting the feature and all REOs and all targets. That information was used by the menu. Now that information is request for a specific feature on demand when the menu is opened for that feature.
=> Improves browser perf when downloading source features

cegs_portal/search/static/search/js/search_results/consts.js, cegs_portal/search/static/search/js/search_results/downloads.js, cegs_portal/search/templates/search/v1/search_results.html
This should keep us from using the incorrect state names
=> Use common state names across search results js

cegs_portal/search/models/dna_feature.py, cegs_portal/search/templates/search/v1/experiments.html, scripts/data_generation/qc_plots/gen_qc_plots.sh
* Fix experiments template to say "Tested Elements". Since experiments are getting mixed we can't say a specific kind of element there.
* remove related name from associated_ccres many-to-many field. This isn't used and we get constant warnings about it
* change .txt files in gen_qc_plots to .tsv. This data is in tsv format, the file names should reflect that.
=> Miscellaneous fixes

cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/urls.py, cegs_portal/search/views/v1/tests/test_non_targeting_reos.py, cegs_portal/search/views/v1/tests/test_source_reg_effects.py, cegs_portal/search/views/v1/tests/test_target_reg_effects.py
Instead of "search/regeffect". These URLs return data related to a feature, not related to an REO, so their URLs should reflect that these are parts of features.
=> Makes feature-related URL paths start with "search/feature"

cegs_portal/search/templates/search/v1/dna_feature.html
This lets users see the gene with more context
=> Adds a "buffer" around gene in the browser

cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
The functionality was already there, we just didn't have the buttons
=> Add TSV/bed download buttons to targeting REO table

cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/partials/_features.html, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/search/views/v1/dna_features.py
Changes were made to accommodate the reference genome selection feature on the dna feature page which caused a few tables with feature data links to break. Added assembly parameter to routes to direct user to the working page.
=> Fixed broken table routing on dna feature page

cegs_portal/search/models/__init__.py, cegs_portal/search/models/dna_feature.py, scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPRa_2022.sh, scripts/data_loading/DCPEXPR0000000009_load_mccutcheon_scCERES_cd8_CRISPRi_2022.sh, scripts/data_loading/db.py, scripts/data_loading/load_experiment.py, scripts/data_loading/tests/conftest.py, scripts/data_loading/tests/test_experiment_saving.py, utils/ccres.py
Part of loading the data is associating tested elements with cCREs for "normalization" purposes. This had been done with a mix of python scripts and `bedtools intersect` but requiring bedtools either directly or implicitly (with `pybedtools`) is kind of overkill when we just need to perform a relatively simple task.
This PR adds the algorithm to match tested elements (or their parents) with cCREs or create new "pseudo" cCREs if no matches are found.
Here's my explanation (from a comment in the code):
To associate features with cCREs we need two lists -- The list of all current cCREs for a genome
assembly and the the list of features. These two lists must be sorted, and must be sorted in the
same manner.
We work our way through both lists linearly, on each iteration moving forward on one …
=> Associated cCREs with tested elements

requirements/base.txt
Django has had some security updates. Whitenoise didn't technically support django 4.2 until version 6.4.
=> Update django and whitenoise

.gitlab-ci.yml, Makefile, compose/production/django/start, compose/production/django/start_huey, config/settings/base.py
This tells whitenoise which file types not to compress during a collectstatic run. We added three binary file types to this because they can be large and just aren't very compressable. Trying to do so slowed down the compresstatic step a lot.
This is a change from using --ignore flags because we don't actually want these files ignored. We want whitenoise to serve them, we just don't want the to be compressed.
=> Add WHITENOISE_SKIP_COMPRESS_EXTENSIONS to settings

scripts/data_loading/DCPEXPR0000000002_ensembl.py, scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_analysis.py, scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_data.sh, scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_experiment.py, scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_analysis.py, scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_data.sh, scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_experiment.py, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_analysis.py, scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_experiment.py, scripts/data_loading/DCPEXPR0000000004_utils.py, scripts/data_loading/DCPEXPR0000000005_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000006_load_bounds_scCERES_mhc_2021.sh, scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022.sh, scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022_analysis.py, scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022_experiment.py, scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_analysis.py, scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_experiment.py, scripts/data_loading/db.py, scripts/data_loading/load_analysis.py, scripts/data_loading/load_experiment.py, scripts/data_loading/tests/conftest.py, scripts/data_loading/tests/test_experiment_saving.py, scripts/data_loading/types.py, utils/experiment.py
The backend/frontend refactor was done just using EXPRs 8 and 9 as the working data. This PR converts the rest of the experiments (2-7) to the new architecture. With a larger set of experiments more useful modifications have been made like:
* Replacing many strings with StrEnums
* performing the gene name->ensembl id mapping work in a separate script so the results can be saved
* Modifying the cCRE association algorithm. If there are parent features, association is performed on those first and then children are associated with their parent's associated cCRE.
* Another cCRE association test
* Move manual test cleanup into a fixture
* Save tested element strand information
* Fix "bulk save" output messages
All these changes on top of the work just removing db access code from the various …
=> Update all loading scripts to use backend/frontend loading arch

.gitlab-ci.yml, Makefile, compose/production/django/start, compose/production/django/start_huey
.ecd (experiment coverage data) and .fd (feature data) files are not directly accessed by the client (the web browser). They are only used by the server and so don't need to be "collected" for django to serve.
=> Don't collect .ecd or .fd files

cegs_portal/search/static/search/js/exp_viz/combo_viz.js, cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/templates/search/v1/experiment.html
"Overview" seems to be understood by the user more than "coverage".
=> Terrminology and css changes

cegs_portal/search/models/experiment.py, cegs_portal/search/models/signals.py, cegs_portal/uploads/views/uploads.py
Uploading experiments on test, because of the different way huey is configured to run vs. locally where the code was developed, didn't work.
These two changes, removing post-save signal receivers and combining experiment and analysis load tasks, fix the two problems.
I think there was a weird interaction between signals and huey that broke things. There's a weak reference that was unable to be serialized.
The experiment and analysis loading needs to be done serially instead of in parallel so combining them into a single task ensures that happens.
=> Remove signal receivers, combine expr/an load tasks

scripts/data_loading/bulk_upload.py
Adds a script that can be used to bulk upload experiment data, or to upload just one experiment.
```
(venv) tc325 data_loading % ./bulk_upload.py --help
usage: bulk_upload.py [-h] -u USERNAME -p PASSWORD [-f FILE] [-a ACCESSION] [--ef EF] [--af AF] host
A script for bulk-uploading experiments/screens to the CCGR Portal
positional arguments:
host                  Portal hostname
options:
-h, --help            show this help message and exit
-u USERNAME, --username USERNAME
Username
-p PASSWORD, --password PASSWORD
Password
Bulk Experiment/Analysis Upload:
-f FILE, --file FILE  A TSV containing locations of the experiment/analysis metadata needed to load the data
Single Experiment/Analysis Upload:
-a ACCESSION, --accession ACCESSION
The experiment accession ID
--ef EF, --experiment-file EF …
```
=> Bulk upload script

cegs_portal/search/templates/search/v1/experiment_list.html
The multi-experiment page is in a good enough shape that we don't need to hide it behind a switch.
=> Remove multi experiment analysis switch

cegs_portal/search/templates/search/index.html
These links didn't work. The single experiment had the wrong accession format and the multi-experiment picked experiments that were analyzed on different assemblies so nothing was shown as they are incompatible.
=> Fix index page links

cegs_portal/search/templates/search/v1/search_results.html
Now that we have more items to filter, the container is being extended. This causes the tables to be pushed off screen and/or makes the browser enable horizontal scrolling.
=> Fixed the filter container over extension

cegs_portal/uploads/views/uploads.py
This fixes a bug in the upload code that causes an error when metadata locations are urls instead of files.
=> Use *_data instead of *_file variables in upload

cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/uploads/data_generation/qq_plot.py
[QQPlot data should be p values, not adjusted p values](https://github.com/ReddyLab/cegs-portal/commit/d875438e93768d2844e2fa6609c32530f260613b) 
Also p values are sometimes 0, so we need to set a floor for them because
log10(0) is not allowed.
[Add y=x line to vega-lite qq plot](https://github.com/ReddyLab/cegs-portal/commit/fcf75c9f91da80356ccd3c822b6c414f8a358bdc) 
This line is a helpful guide for folks using the qq plot
for QC purposes.
=> QQ plot improvements

cegs_portal/search/static/search/js/exp_viz/combo_viz.js, cegs_portal/search/static/search/js/exp_viz/consts.js, cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/static/search/js/exp_viz/ui.js, cegs_portal/search/templates/search/v1/experiments.html
Adds a dropdown to the multi-experiment page that allows users to select between unioning and intersecting the experiment coverage data for multiple experiments.
=> Adds ability to union experiment results together

compose/local/django/Dockerfile, compose/production/django/Dockerfile
CI Scan was failing due to some security vulnerabilities in OS-level libraries, so we have to update the base image.
=> Update docker image to fix CVEs

cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/static/search/js/files.js, compose/local/django/Dockerfile, compose/production/django/Dockerfile
Clicking around on the filter check boxes can cause multiple fetches to be "in flight"
at the same time. These may not necessarily return in the expected order (i.e. the most
resent "state" of the filter might finish before other states). This can result in an experiment
list that doesn't reflect the current state of the facet checkboxes.
This change adds a way to cancel getJson fetches and uses this to cancel previous
facet filter fetches when creating a new one so that only the most recent fetch finishes.
=> Experiment list facet query

cegs_portal/search/view_models/v1/experiment.py
The Experiment list JSON returns biosample information. Retrieving this info
was causing an n+1 query issue. Prefetching fixes that.
=> Experiment list speedup

cegs_portal/conftest.py, cegs_portal/search/views/v1/tests/test_experiment_collection.py
The "client" is quite slow-- it takes about 2s/test. By using RequestFactory/RequestBuilder we speed this up so all the same tests take about 1s total. That's not fast-fast, but it's much better.
We kept a "client" test to make sure the end-to-end still works.
=> Speed up exp coll view tests

compose/local/django/Dockerfile, compose/production/django/Dockerfile, requirements/base.txt
The default version of Twisted that gets installed as a dependency of daphne relies on the 'cgi' module. This 'cgi' module will be removed in python 3.13, which will be released soon. This newer version of Twisted has removed usage of that module.
=> Update Twisted to newer version

cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/views/v1/dna_features.py
There were a couple of problems:
1) The wrong assembly was the default. It should have been hg38 
2) Genoverse was trying to use hg19/hg38 instead of grch37/grch38
These changes fix both
=> Fix DNA Feature page assembly problems

README.md, cegs_portal/search/admin.py, cegs_portal/uploads/forms/__init__.py, config/settings/base.py, requirements/base.txt, requirements/local.txt
This upgrades django to 5.1, plus fixes all the deprecation warnings. They mainly had to do with the new "assume_schema" argument to URLField. the argument was added in Django 5.0 with a default of "http" and in 6.0 it will change to "https". I'm not sure we're ready for that to happen, so I explicitly set it to 'http".
=> Upgrade django to 5.1

cegs_portal/search/static/search/js/exp_viz/ui.js, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/static/css/project.css, cegs_portal/static/css/project.css.tw, cegs_portal/templates/base.html
* Sliders expand to with of container
* body padding is 1 on small screens
* QC/Analysis graph boxes are centered and the width of the content on larger screens
* File tables still show container padding when overflowing their containers
* Description margins/padding is 0
* Container padding is 10x10 on small screens and 20x30 (or 30x20, whichever) on all other screens
=> Experiment page css

cegs_portal/search/view_models/v1/tests/test_search.py
These tests were in a file that wasn't discovered by pytest due to the name not starting with "test_". We rename this file so pytest picks it up.
Since it hadn't been run due to the aformentioned issue when "target only" reg effects were removed from the reg_effects fixture the tests broke but hadn't been fixed.
=> Fix search view model tests

cegs_portal/search/models/__init__.py, cegs_portal/search/models/experiment.py, cegs_portal/uploads/views/tests/conftest.py
Without these facets these tests fail. The reason there's a check to see if the facets already exist is because they are created when pytest created the DB (i.e. `pytest --create-db` is run) but are deleted when pytest is done. So the shouldn't be created when pytest is run with --create-db but they should otherwise.
=> Adds facets to upload experiment tests

cegs_portal/search/models/dna_feature.py, cegs_portal/uploads/data_loading/analysis.py, cegs_portal/uploads/data_loading/compressed.py, cegs_portal/uploads/data_loading/experiment.py, cegs_portal/uploads/data_loading/experiment_metadata.py, cegs_portal/uploads/forms/__init__.py, cegs_portal/uploads/validators.py, cegs_portal/uploads/view_models.py, cegs_portal/uploads/views/uploads.py
It's annoying to rely on 3rd party hosting to get data into the portal
all the time (especially when, as of the data of these commits, the lab
doesn't have any 3rd party hosting).
This code adds support for uploading a tar.gz file with the metadata AND
data included.
The backend untars the file and then loads the file as usual, more or less.
=> Allow users to upload data from compressed archives

cegs_portal/search/static/search/js/genoverse.js
This sets the initial browser with to most of the window width (matching the padding of the page). Additionally, it makes genoverse resize when the window resizes, to a minimum of 500px. That's just a guess at the smallest size that could still be useful.
=> Make genoverse better match window width

cegs_portal/search/json_templates/v1/feature_reg_effects.py, cegs_portal/search/json_templates/v1/tests/test_feature_reg_effects.py, cegs_portal/search/static/search/js/genoverse.js
When a user clicks on a tested regulatory element we want to show What screen type(s) were run on the element in addition to the already included effect size.
=> Show screen type in tested RE menu

cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/dna_features.html, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/non_targeting_reos.html, cegs_portal/search/templates/search/v1/partials/_features.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/static/css/project.css, cegs_portal/static/css/project.css.tw
* The genoverse browser was a little too wide for its container.
The containers horizontal scroll bar was always showing and genoverse
went off the right edge.
* Adjusts how .page-header-w-icon works, so the left margin isn't
built in. This lets us remove the margin when the screen is narrow.
* Keeps the feature table width within the horizontal bounds
of the screen.
* Updates the experiment list so that the experiment boxes are the
full width of the screen when the screen is narrow.
* The genoverse container on the dna_features page didn't overflow
so when the screen was narrow it would go off the edge.
=> Responsive UI tweaks

cegs_portal/search/views/v1/tests/test_search.py
Changes to the HTML could introduce blank spaces, making it difficult to update the HTML in the test since you’d have to account for those spaces. This update eliminates the need to consider blank spaces when running the test.
=> Fixes test by removing blank spaces

cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/dna_features.py, cegs_portal/search/models/__init__.py, cegs_portal/search/models/dna_feature.py, cegs_portal/search/models/tests/dna_feature_factory.py, cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/static/search/js/test/test_genoverse_standin.py, cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/view_models/v1/dna_features.py
This track shows the location of SCREEN cCREs. They are color coded according to SCREEN category (pELS, dELS, etc.).
=> Add cCRE track to genoverse

cegs_portal/search/json_templates/v1/dna_features.py, cegs_portal/search/json_templates/v1/tests/test_dna_features.py, cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/static/search/js/test/test_genoverse_standin.py, cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/static/css/project.css
Reduces "whitespace" in Genoverse browser mainly by replacing legends with tooltips. It also fixes a couple of inconsistencies and bugs.
* The colors for the two gene "zoom levels" didn't match -- a gene would have one color when the exons were visible and another when they weren't.
* This is related to the second bug -- the gene types weren't always correct. When the exons were visible we were actually using the transcript type, which isn't the same as the gene type.
* Also a small issue with menus and CSS overflow is fixed
Before:
After:
More After:
=> Reduce Genoverse whitespace

cegs_portal/templates/base.html
This CSS is included in every page, and thus applies to every image. But it's really only for the footer images.
It was causing problems with the genoverse browser when the screen got too narrow.
=> Apply margins to only footer images

cegs_portal/templates/base.html
The gray background was replaced with the search bar background color.
=> fix navbar search bar icon

cegs_portal/search/templates/search/index.html
This increases the screen width before the cards on the index page wrap. It resets it what we want, after a recent change changed the behavior.
Before:
After:
=> Makes #card-container full width of page

cegs_portal/search/static/search/js/exp_viz/render.js
When there's only one item in the bucket the coverage color for that bucket is black, which is incorrect. It doesn't match the color in the legend. This is because of a divide by 0 that happens because the "range" of the value is 0, as there's only one.
So we match the behavior of the legend in this case and return 0.5, which makes the color the middle value of the color gradient for that bucket.
Also adds commas at the end of lists, because that's what Prettier, the JS formatter, does.
Before:
After:
=> Fix coverage color when only 1 item in bucket

cegs_portal/search/static/search/js/genoverse.js
On iOS devices the "resize" event is dispatched when scrolling, for some reason. In order to avoid constant "resizes" (that are to the same width, but still make network calls to refetch the data) we keep track of the current "full width" and only resize if the new computed width is different.
=> Only resize if the width actually changed

compose/production/django/start, scripts/refresh_static_files.sh
After data is uploaded gunicorn needs to be reset because the whitenoise middleware we use to serve static files doesn't automatically pick up new files. It only checks for new files at load.
=> Adds more gunicorn works, script to restart gunicorn

cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/search_results.html
On mobile devices, scrolling can sometimes trigger a resize event, which might be causing the tabs to collapse unexpectedly. We are now comparing the current screen size with the previous one to determine if the tabs should collapse or not.
=> Fix mobile dropdown issue

cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/static/css/project.css
Reverted to the column structure to ensure all content fits on the same row within the container. Looks cleaner with more space.
=> Responsive dna_feature profile table

cegs_portal/search/json_templates/v1/dna_features.py, cegs_portal/search/json_templates/v1/tests/test_dna_features.py, cegs_portal/search/static/search/js/genoverse.js, cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/search/views/v1/dna_features.py, cegs_portal/search/views/v1/non_targeting_reos.py, cegs_portal/search/views/v1/reg_effects.py, cegs_portal/task_status/views.py, cegs_portal/utils/__init__.py
New Coverage track:
This track shows all the features that are sources for REOs.
A new `feature_property` was added to the featureloc endpoint. Since there were so many `feature_properties` this got cleaned up a little by replacing all the strings with a StrEnum containing the feature_properties. This will help us keep straight what properties exist and avoid typos, since python will complain if we try to use a non-existent LocSearchProperties.
Random "leave it better than you found it"s:
* a feature's parent is always used (the parent.name property is always accessed) so we always select_related("parent")
* other parent properties are only used when the parent_info feature property is sent, so those are hidden behind that `feature_property` query
* Gene, Tested Element, and Transcript …
=> Coverage track

cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/experiments.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/static/css/project.css
When users log in, certain buttons alter the intuitive layout design on smaller screens. Additionally, users on smaller devices are less likely to download or upload data.
Highlight regions button removed:
Highlight regions and download buttons removed:
Download Region Data button removed:
Download data from selected experiments button removed:
=> Remove download/upload buttons on smaller screens

compose/production/django/start
We tried 8, but kept getting a postgres "too many connections" error, so we dropped to 4. In the future we might be able to go back up to 8 if we use something like pg_bouncer to pool connections
=> Adjust gunicorn worker count down

cegs_portal/get_expr_data/conftest.py, cegs_portal/get_expr_data/tests.py, cegs_portal/get_expr_data/view_models.py, cegs_portal/search/conftest.py, cegs_portal/search/json_templates/v1/search_results.py, cegs_portal/search/json_templates/v1/tests/test_search_results.py, cegs_portal/search/models/tests/dna_feature_factory.py, cegs_portal/search/models/utils.py, cegs_portal/search/view_models/v1/dna_features.py, cegs_portal/search/views/v1/search.py, cegs_portal/search/views/v1/tests/conftest.py, cegs_portal/search/views/v1/tests/test_search.py, cegs_portal/uploads/data_loading/analysis.py, cegs_portal/uploads/data_loading/db.py, cegs_portal/uploads/data_loading/experiment.py, cegs_portal/uploads/views/tests/conftest.py, compose/local/django/Dockerfile, compose/production/django/Dockerfile, config/settings/production.py, requirements/local.txt, requirements/production.txt, scripts/data_loading/DCPEXPR0000000001_load_bounds_2021_scceres_analysis.py, scripts/data_loading/DCPEXPR0000000001_load_bounds_2021_scceres_experiment.py, scripts/data_loading/DCPEXPR0000000002_ensembl.py, scripts/data_loading/db.py, scripts/data_loading/load_analysis.py, scripts/data_loading/load_experiment.py, scripts/data_loading/load_gencode_gff3_data.py, scripts/data_loading/tests/conftest.py, utils/ccres.py
Psycopg 3 includes the ability to pool database connections. We need to use this in production to support multiple gunicorn workers, because even at 4 we're sometimes getting "too many client" errors.
Psycopg 3 made some changes:
* replaced several copy_ functions with a single copy object
* Array values are returned as python lists rather than a single string
* Int4Range is no longer automatically cast to NumericRange
So there are quite a few code changes! Thank goodness for tests!
=> Update psycopg from 2 to 3

cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/templates/search/v1/dna_features.html
This will let folks drag and drop bigwigs on the browser to see their data alongside what's in the portal.
=> Add filedrop plugin to all genoverse browsers

config/settings/production.py
This should have been all caps: https://docs.djangoproject.com/en/5.1/ref/databases/#postgresql-connection-settings
=> Change "options" to "OPTIONS"

config/settings/production.py
Connection pooling and persistent connections are mutually exclusive. Removing this option disabled persistent connections.
=> Disable persistent connections

cegs_portal/get_expr_data/view_models.py
The macOS filesystem can't handle filenames longer than 255 characters and the database field storing filenames can't handle names longer than 256 characters, so we truncate names that are too long.
=> Truncate filenames too long for the DB/filesystem

cegs_portal/search/static/search/js/exp_viz/render.js
Two issues with bucket colors:
1. The "count" legend colors were left/right swapped with the other two legends
2. The "fade" colors weren't just faded, but also moved around the HSL color wheel.
This also simplifies the color function because we're usng the same set of colors for all three coverage types.
=> Fix bucket colors

cegs_portal/search/static/search/js/genoverse.js
Instead of a curve. The curve was too reminiscent of DNA splicing diagrams.
New:
Old:
=> Make subfeature connections a line

cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/view_models/v1/experiment.py, cegs_portal/search/views/v1/experiment.py
* adds/removes facets to the query string as they are checked/unchecked.
* Sets the check boxes to the facets specified in the URL when the
page is loaded.
Previously all the facets were just "or"d together when filtering experiements. This change makes values within a single facet "or"d and between facets "and"ed (e.g.,  ("Perturb-Seq" OR "Flow-FISH Crispr screen") AND "K562" AND "hg38")
This functionality is meant to match the facet box on the search results page.
=> Fix experiment list facets

cegs_portal/search/templates/search/v1/partials/_search_feature_counts.html, cegs_portal/search/templates/search/v1/partials/_sig_reg_effects.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/search/views/v1/tests/test_search.py
The ‘Show results for a genomic region’ card on the homepage matches the ‘Results’ for chr11: 33,858,576 - 33,892,076 (region) text shown on the search results page. Describing it as ‘Top significant effect observation’ might be more descriptive of what we are showing the user. Additionally, using ‘Filter Region’ could bring more clarity. Our goal is to make the portal as intuitive as possible.
=> Text changes for clarity

cegs_portal/search/conftest.py, cegs_portal/search/view_models/v1/reg_effects.py, cegs_portal/search/views/v1/tests/test_source_reg_effects.py, cegs_portal/search/views/v1/tests/test_target_reg_effects.py
Significance is also the Corrected p-Value. Previously these were ordered by accession id, which doesn't make much sense.
=> Order DNA Feature REOs by significance

cegs_portal/search/templates/search/v1/partials/_multi_experiment_index.html
The "Combine Experiments" sidebar in the multi-experiment selection modal should be uncollapsed because these fields are always needed to use this modal.
=> "Combine Experiments" sidebar starts expanded

cegs_portal/search/static/search/js/exp_viz/chromosomeSvg.js, cegs_portal/search/static/search/js/exp_viz/combo_viz.js, cegs_portal/search/static/search/js/exp_viz/consts.js, cegs_portal/search/static/search/js/exp_viz/exp_viz.js, cegs_portal/search/static/search/js/exp_viz/render.js, cegs_portal/search/static/search/js/exp_viz/ui.js
After a user zoomed in they couldn't tell where the bucket they selected was. This adds a basic highlight to show the user which 100kb buckets are in the 2mb bucket they selected.
=> Highlight Selected Bucket

cegs_portal/search/templates/search/index.html
Currently, it appears that people understand ‘summarize’ better than ‘show’ for context on this card.
=> Changing text from "Show" to "Summarize".

cegs_portal/search/conftest.py, cegs_portal/search/static/search/js/test/test_genoverse_standin.py
The features need to have their significant_reo property set. I should have run pytest myself, but I'm also surprised that gitlab didn't run the CI pipeline for the branch from #433  which also would have caught it.
=> Fix test failure that slipped through PR #433

cegs_portal/search/static/search/js/genoverse.js
This makes the browser look a little better.
Before:
After:
=> Add border to all tested elements track

cegs_portal/search/templates/search/v1/dna_feature.html, cegs_portal/search/views/v1/dna_features.py
The proximal REO table is loaded async via htmx. But we were still doing a count and actually loading the reos.
This uses the .exists method to avoid actually loading all the proximal REOs and removes the pagination code that performs the count.
These problems were especially noticable on MYB, which has a lot of REOs.
=> Remove proximal REO queries from dna feature page

cegs_portal/search/templates/search/v1/non_targeting_reos.html, cegs_portal/search/templates/search/v1/partials/_reg_effect.html, cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html, cegs_portal/static/css/project.css
These tables were stuck at always being the "small" width, regardless of container size. This change lets them be "full width" once the width is the tailwind "medium".
=> Let tables be full width

cegs_portal/search/json_templates/v1/experiment.py, cegs_portal/search/json_templates/v1/tests/test_experiment.py, cegs_portal/search/static/search/js/experiment_list/facet_filter.js, cegs_portal/search/templates/search/v1/experiment_collection.html, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/partials/_experiment_index.html, cegs_portal/search/templates/search/v1/partials/_experiment_list.html, cegs_portal/search/templates/search/v1/partials/_multi_experiment_index.html, cegs_portal/search/view_models/v1/experiment.py, cegs_portal/search/views/v1/experiment.py
This adds the experiment assembly to the experiment box used when listing experiments.
It also takes the opportunity to do some refactoring and use htmx+template for the experiment list rather than a bunch of awkward javascript.
Finally, it fixes an issue with the URL changing when facets are selected from experiment list modal views.
NOTE: It might be helpful to hide whitespace changes when reviewing this.
=> Add assembly info to experiment box

cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/templates/search/v1/experiment_list.html, cegs_portal/search/templates/search/v1/experiments.html, cegs_portal/search/templates/search/v1/search_results.html, cegs_portal/static/css/project.css, cegs_portal/static/css/project.css.tw
Instead of hiding logged-in only actions completely we should show that they exist, but users need to login to use them. That way people know the functionality is there.
=> Show logged-in-only actions with message

cegs_portal/search/admin.py, cegs_portal/search/models/experiment.py
Experiment Collection and Experiment Relation both had the default change list items, which aren't very descriptive. This improves them both while avoiding and n+1 query issue for Experiment Relations
Before:
After:
=> Improve admin changelist views

cegs_portal/search/templates/search/v1/experiment.html
Adds some UI to the experiment page that shows the collections an experiment is a part of.
=> Add collection info to experiment UI

config/settings/base.py
For uploading data 2.5 MB (the default) is often too small.
=> Increase file upload size limit

cegs_portal/search/static/search/js/dna_feature/closest_feat_type.js
Some genes have no "closest features" and that tab won't exist.
=> Don't unconditionally set up closest feature types

cegs_portal/search/models/experiment.py, cegs_portal/search/templates/search/v1/experiment.html, cegs_portal/search/views/v1/experiment.py, cegs_portal/search/views/v1/tests/test_experiment.py, cegs_portal/static/css/project.css
This changes came about as a result of adding the liftover related experiments
1) Archived experiments can be viewed, but with an "This experiment has been archived" banner
2) Linebreaks are shown in the related experiments description.
3) Fixed a bug when saving experiments via the admin UI
=> Experiment display changes
