- cegs_portal/search/static/search/js/ds.js
- cegs_portal/search/static/search/js/ds.test.js
- package-lock.json
- package.json
This AVL tree (a balanced binary search tree) will be the basis for our range tree.
The implementation for the AVL is based on the one in Knuth's AoCP vol. 3.
1d range trees are balanced binary search trees that store values in
leaves, using nodes as "guideposts" for finding the desired values.
See https://en.wikipedia.org/wiki/Range_tree for more information
> Add AVL-tree based range tree

- cegs_portal/search/json_templates/__init__.py
- cegs_portal/search/json_templates/v1/dna_feature.py
- cegs_portal/search/json_templates/v1/dna_features.py
- cegs_portal/search/json_templates/v1/experiment.py
- cegs_portal/search/json_templates/v1/reg_effect.py
- cegs_portal/search/json_templates/v1/search_results.py
- cegs_portal/search/json_templates/v1/tests/test_dna_feature.py
- cegs_portal/search/json_templates/v1/tests/test_dna_features.py
- cegs_portal/search/json_templates/v1/tests/test_experiment.py
- cegs_portal/search/json_templates/v1/tests/test_reg_effect.py
- cegs_portal/search/json_templates/v1/tests/test_search_results.py
- cegs_portal/search/views/v1/experiment.py
JSON endpoints hadn't been tested in a while. We should write some tests against the actual endpoints and not just against the template functions -_-. Various recent changes broke several of the endpoints. I think they should all be fixed now.
> Fixes JSON endpoints

- cegs_portal/search/view_models/v1/search.py
- cegs_portal/search/views/v1/search.py
- cegs_portal/search/views/v1/tests/test_search.py
- config/settings/base.py
These check that some basic search functionality works. Found a bug!
* Discovered an infinite loop condition for malformed queries
> Search url tests

- cegs_portal/search/conftest.py
- cegs_portal/search/json_templates/v1/feature_reg_effects.py
- cegs_portal/search/json_templates/v1/tests/test_feature_reg_effects.py
- cegs_portal/search/templates/search/v1/target_reg_effects.html
- cegs_portal/search/urls.py
- cegs_portal/search/view_models/v1/reg_effects.py
- cegs_portal/search/views/v1/__init__.py
- cegs_portal/search/views/v1/reg_effects.py
- cegs_portal/search/views/v1/tests/test_target_reg_effects.py
The endpoint is similar to /search/regeffect/source. Given a DNA Feature it returns all the REOs for which that DNAFeature is a target.
> Creates a /search/regeffect/target endpoint

- cegs_portal/search/static/search/js/tables.js
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/view_models/v1/dna_features.py
- cegs_portal/search/view_models/v1/reg_effects.py
- cegs_portal/search/views/v1/dna_features.py
Adds paging to the DNA Feature "Target of" table of REOs. This is important because some DNA Features are the "target" of lots of REOs.
> Add "target of" pagination to DNA Feature page

- compose/local/django/Dockerfile
- compose/production/django/Dockerfile
- requirements/base.txt
3.11 will improve performance slightly. It will also allow us to use some of the new 3.10 syntax features, like pattern matching.
> Update to use python 3.11

- extensions/exp_viz/Cargo.lock
- extensions/exp_viz/Cargo.toml
- extensions/exp_viz/src/filter.rs
- extensions/exp_viz/src/filter_data_structures.rs
- extensions/exp_viz/src/merge.rs
This particular solution does incur a performance penalty, so I'll be taking a look way to speed it up.
*UPDATE* after some actual testing, it doesn't seem to incur much -- a few milliseconds? so I think its fine.
> Fixes issue with zoomed-in view highlights not working

- cegs_portal/get_expr_data/conftest.py
- cegs_portal/get_expr_data/tests.py
- cegs_portal/get_expr_data/urls.py
- cegs_portal/get_expr_data/view_models.py
- cegs_portal/get_expr_data/views.py
This is similar to the endpoint for getting REOs in lots of regions, but this one is synchronous and works on one region at a time.
> Creates a new endpoint for getting REOs in a region

- cegs_portal/search/templates/search/index.html
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/dna_features.html
- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/templates/search/v1/source_reg_effects.html
- cegs_portal/search/templates/search/v1/target_reg_effects.html
- cegs_portal/static/css/project.css
- cegs_portal/templates/base.html
Accidentally broke the centering of the search box on index.html.
This also improves the experiment page CSS a bit and fixes the padding on all the pages.
> Fixes search box centering

- config/settings/qa.py
I'm getting an application gateway error in the test environment even though nothing has changed, settings wise, except this.
> Set qa DEBUG back to True

- cegs_portal/get_expr_data/conftest.py
- cegs_portal/get_expr_data/tests.py
- cegs_portal/search/conftest.py
- cegs_portal/search/views/v1/tests/test_dna_features.py
- cegs_portal/search/views/v1/tests/test_experiment.py
- cegs_portal/search/views/v1/tests/test_experiment_coverage.py
- cegs_portal/search/views/v1/tests/test_reg_effects.py
- cegs_portal/search/views/v1/tests/test_source_reg_effects.py
- cegs_portal/search/views/v1/tests/test_target_reg_effects.py
- cegs_portal/tasks/conftest.py
- cegs_portal/tasks/tests/test_tasks.py
This class will reduce the amount of boilerplate code used to create logged-in clients for testing, as evidenced by the changes to test_dna_features.py
> Adds SearchClient class for testing

- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/static/css/project.css
- config/settings/base.py
Updated/Added QC graphs on experiment page
> Add qcgraphs to experiment page

- cegs_portal/static/css/project.css.tw
- cegs_portal/templates/account/login.html
- cegs_portal/templates/account/password_reset.html
- cegs_portal/templates/account/signup.html
Styled pages with forms for login, password reset, and signup pages. More pages may fall under this branch
> Styled pages with forms for login, password reset, and signup pages.

- .pre-commit-config.yaml
- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/static/css/project.css
- scripts/data_generation/qc_plots/gen_qc_plots.sh
- scripts/data_generation/qc_plots/histogram.py
- scripts/data_generation/qc_plots/qq_plot.py
- scripts/data_generation/qc_plots/volcano_plot.py
- scripts/data_loading/load_all.sh
Scripts to generate data for QC and analysis plots
> Scripts to generate data for QC and analysis plots

- config/settings/production.py
- config/settings/qa.py
This is a security recommendation by OWASP and the praetorian team
> Decrease session length from 3 weeks to 20 minutes.

- cegs_portal/search/static/search/js/exp_viz/exp_viz.js
- scripts/data_generation/gen_experiment_coverage_viz.sh
Manifest files are created by [cov_viz_manifest](https://github.com/ReddyLab/cov_viz_manifest)
> Generate and use default facets for experiments

- cegs_portal/search/static/search/js/tables.js
- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
This starts to get the page look in-line with the overall look we're changing to.
> Update search results look a bit

- cegs_portal/search/static/search/js/exp_viz/exp_viz.js
Also delete some commented out code.
> Fix bug stopping users from searching from exp cov

- cegs_portal/search/templates/search/v1/experiment.html
Also makes the volcano and qq plots match in color and size.
> Moves QQ plot to analysis tab

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/views/v1/dna_features.py
Now the logic deciding which tabs to show is in the view. The template has been updated to use the new "tabs" data.
> Move "what tabs are showing" logic to view

- cegs_portal/get_expr_data/view_models.py
- cegs_portal/search/static/search/js/exp_viz/downloads.js
- cegs_portal/search/static/search/js/exp_viz/exp_viz.js
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/views/v1/experiment.py
- cegs_portal/static/css/project.css
If a user is logged in they can download experiment data for regions they define in a bed file for all (shown) experiments.
> Add experiment data download for multiple experiments

- cegs_portal/search/templates/search/v1/search_results.html
This enables users to drop certain kinds of files onto the browser which will open a track to show the file data.
> Enables file dropping in genoverse browser

- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/static/css/project.css
Also changes font-family to remove Arial.
> Moves Experiment info into page header

- cegs_portal/get_expr_data/tasks.py
We shouldn't keep these files around forever.
> New task to remove gen'd expr data > 7days old

- .gitlab-ci.yml
It gets run in all other branches
> We (hopefully) don't need to run pytest in prod

- .gitlab-ci.yml
> Another flake8 command modification

- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/view_models/v1/search.py
- cegs_portal/search/views/v1/tests/test_feature_counts.py
The list of feature counts should combine all the experiment sources
(DHSs, CARs, gRNAs, and anything else we end up with) into a single
category.
> Combine source feature counts into one category

- cegs_portal/search/static/search/js/utils.js
- cegs_portal/search/templates/search/v1/search_results.html
* Resets the facet values when page is realoaded
* Facets start shown (this may change as we add more)
* The arrows don't move when toggled between up and down
* the box stays the same width regardless of how wide the window is
* Fixed the throttle function, which wasn't applying arguments correctly
> Fix some ui bugs with the facet bar

- .gitlab-ci.yml
- config/urls.py
No more favicon.ico 404 errors
> Add redirect for favicon

- cegs_portal/search/templates/search/v1/search_results.html
There is basically a 0% chance we use this plot UI
> Removes plot code from search page

- cegs_portal/search/static/search/js/tables.js
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/dna_features.html
- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
The browser will only show up if there is just one feature.
I also fixed some awkward table widths. They looked terrible with the browser.
> Adds genome browser to dna feature (gene) pages

- cegs_portal/search/static/search/js/tables.js
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/non_targeting_reos.html
- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
If the "Regulatory Effects" tab has no regulatory effects, show a message stating as much.
With regulatory effects:
Without regulatory effects:
> Always show REO tab

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/partials/_reg_effect.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
- cegs_portal/templates/account/login.html
- cegs_portal/templates/account/logout.html
- cegs_portal/templates/account/password_reset.html
- cegs_portal/templates/account/signup.html
This line is specifically used under the titles of content sections. "title separator" makes this clearer.
> Rename "faded line" to "title separator"

- cegs_portal/search/static/search/js/tables.js
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
- cegs_portal/search/templates/search/v1/partials/_reg_effect_source.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
Previously it was something like "gRNA (chr1:1-1000:-)" which makes a little smiley face. This change is to "gRNA @ chr1:1-1000:-" which is maybe clearer
> Changes how feature types + locations are shown

- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
Also changes x-padding everywhere to be 30 px like the experiment list padding was.
I think it looks slightly better.
> Use regular container class in experiment list

- cegs_portal/search/templatetags/custom_helpers.py
- cegs_portal/search/tsv_templates/v1/non_targeting_reos.py
Added the first required fields and added feature name as name
> Adding bed6 format to tsv download

- cegs_portal/search/static/search/js/experiment_list/drag_drop.js
This element only exists if the user is logged in.
> Check for the existence of dataDownloadLink element

- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
- cegs_portal/search/templatetags/custom_helpers.py
- cegs_portal/search/tsv_templates/v1/non_targeting_reos.py
- cegs_portal/search/views/custom_views.py
- cegs_portal/search/views/v1/non_targeting_reos.py
- cegs_portal/static/css/project.css
> Added table download feature for bed file format

- cegs_portal/search/static/search/js/experiment_list/facet_filter.js
- cegs_portal/search/templates/search/v1/experiment_list.html
Added svg_icon to experiment-filter and removed the change color hover effect.
Before:
After:
> Further CSS updates to Experiment List Page

- cegs_portal/search/helpers/options.py
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templatetags/custom_helpers.py
- cegs_portal/search/tsv_templates/v1/non_targeting_reos.py
- cegs_portal/search/tsv_templates/v1/reg_effects.py
- cegs_portal/search/views/v1/reg_effects.py
The table data and the tsv data are not in sync. Edited the data to show the correct figures and headers from the table. Created another tsv_renderer for TargetEffectsView because the Regulatory Effects Table has its own specific data in it.
> Editing data in tsv files for regeffect tables

- extensions/exp_viz/Cargo.lock
- extensions/exp_viz/Cargo.toml
A couple of bucket creation bugs were fixed
> Use updated exp_viz library

- requirements/base.txt
- requirements/local.txt
The CI scan step was failing because of these
> Bump versions to incorporate security bug fixes

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/views/v1/dna_features.py
> Adding checkbox search function

- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022.sh
- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_analysis.py
- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_experiment.py
- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPRa_2022.sh
- scripts/data_loading/DCPEXPR0000000009_load_mccutcheon_scCERES_cd8_CRISPRi_2022.sh
- scripts/data_loading/load_all.sh
This PR make three major changes
* Loads data using "COPY" techinque
* Associates gRNA with a DHS
* Associates said DHS with a cCRE, if possible
> Associate gRNAs with DHS for DCPEXPRs 8, 9

- scripts/data_loading/DCPEXPR0000000002_load_klann_2021_scceres_analysis.py
- scripts/data_loading/DCPEXPR0000000003_load_klann_2021_wgceres_analysis.py
- scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_analysis.py
- scripts/data_loading/DCPEXPR0000000004_load_bounds_scCERES_mhc_2021_experiment.py
- scripts/data_loading/DCPEXPR0000000007_load_siklenka_atacstarrseq_K562_2022_analysis.py
- scripts/data_loading/load_all.sh
None of these fixes/changes are very large and I don't think they warrant a full PR. I have broken them down into multiple commits so it's easier to see the changes on their own.
[Add some comments and timing info to load_all](https://github.com/ReddyLab/cegs-portal/commit/8c4ebed1b33b4a2efb76486f3fdc20a54240afd1)
[Normalize how caching query results works](https://github.com/ReddyLab/cegs-portal/pull/242/commits/7b4a5369684d1055a7654e80c315703535e9c082)
[Cache target genes](https://github.com/ReddyLab/cegs-portal/pull/242/commits/2b2de03f6d6f4976a586bcf6a296397c8917e772)
[Associate DHSs, not gRNAs with cCREs](https://github.com/ReddyLab/cegs-portal/pull/242/commits/ea82ba993e0f58777c3f3f36e7e7a1c78908f041)
> Miscellaneous Loading fixes

- cegs_portal/search/views/v1/experiment_coverage.py
- compose/local/django/Dockerfile
- compose/production/django/Dockerfile
- extensions/exp_viz/Cargo.lock
- extensions/exp_viz/Cargo.toml
- extensions/exp_viz/src/filter_data_structures.rs
This re-allows filtering by chromosome, which was broken by the great filter datastructure refactor.
> Passes chrom index to filter

- cegs_portal/search/templates/search/v1/partials/_reg_effect.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
The previous link wasnt working and extra symbols were removed
> Fixes to pagination reo tables

- compose/local/django/Dockerfile
- compose/local/django/start
- compose/production/django/start
- requirements/base.txt
- requirements/production.txt
This will make the QA environment run a bit more like the production environment. We don't need to reload on code changes anyway, since we don't make code changes directly on the QA server.
> Modifies deployment for QA

- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/tsv_templates/v1/search_results.py
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/search/views/v1/non_targeting_reos.py
- cegs_portal/search/views/v1/search.py
- cegs_portal/search/views/v1/tests/test_search.py
- cegs_portal/static/css/project.css
This table is accessed from the search results page
> Adds tsv and bed download option to sig reo count tables

- cegs_portal/search/models/tests/dna_feature_factory.py
- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/tsv_templates/v1/dna_features.py
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/search/views/v1/tests/test_dna_features.py
Adds TSV/BED6 downloads to feature loc tables
> Add TSV/BED download to featureloc table

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/views/v1/dna_features.py
> Reference genome selection

- cegs_portal/search/conftest.py
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/search/tsv_templates/v1/reo_features.py
- cegs_portal/search/urls.py
- cegs_portal/search/view_models/v1/reg_effects.py
- cegs_portal/search/views/v1/__init__.py
- cegs_portal/search/views/v1/reg_effects.py
- cegs_portal/search/views/v1/tests/test_dna_features.py
- cegs_portal/search/views/v1/tests/test_reg_effects.py
This required creating two new endpoints and some new view model methods.
> Adds tsv downloads of regeffect sources/targets

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/search/views/v1/search.py
Removed select reference genome default to display ref_genome itself
> Replace dna_feature header ref_genome with dropdown

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/views/v1/dna_features.py
We are now returning one feature per page so some forloops and if statments arent needed
> Removing code for multiple features

- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_analysis.py
- scripts/data_loading/DCPEXPR0000000008_load_mccutcheon_scCERES_cd8_CRISPR_2022_experiment.py
- scripts/data_loading/load_analysis.py
- scripts/data_loading/load_experiment.py
- utils/experiment.py
Changes 
```python
with open(analysis_filename) as analysis_file:
analysis_metadata = AnalysisMetadata.json_load(analysis_file)
observations_rows = get_observations(analysis_metadata)
analysis = Analysis(analysis_metadata, observations_rows)
analysis.save()
```
to
```python
metadata = AnalysisMetadata.file_load(analysis_filename)
Analysis(metadata).load(get_observations).save()
```
(and the same for Experiment)
> Improve load api

- cegs_portal/search/static/search/js/search_results/consts.js
- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/views/v1/search.py
- cegs_portal/static/css/project.css
Added  tabs for region summary and dna_features data
> Adding tabs, dna_feature search and table to page

- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects_table.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/views/v1/search.py
> Added all effects tab, table and pagination

- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
- cegs_portal/templates/account/login.html
- cegs_portal/templates/account/password_reset.html
- cegs_portal/templates/account/signup.html
- cegs_portal/uploads/forms/__init__.py
- cegs_portal/uploads/templates/uploads/upload.html
- cegs_portal/uploads/templates/uploads/upload_complete.html
- cegs_portal/uploads/validators.py
- cegs_portal/uploads/views/uploads.py
- config/settings/base.py
- config/urls.py
- requirements/base.txt
This page was removed because it wasn't used, but now it will be!
This adds the page and updates the form and its styling.
Because it updates crispy forms and uses a new "template pack" other crispy forms will have updated looks.
> Re-adds and updates file upload page

- cegs_portal/search/templates/search/index.html
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/dna_features.html
- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects_table.html
- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
- cegs_portal/search/templates/search/v1/partials/_reg_effect.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/templates/search/v1/source_reg_effects.html
- cegs_portal/search/templates/search/v1/target_reg_effects.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
Features table didnt have message for no results, dna feature profile table location link now identifiable. These are a few of the changes made in this PR. We have made many changes the past few months so we are applying those changes to other pages as well
> Frontend changes

- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/validators.py
- cegs_portal/search/view_models/v1/experiment.py
- cegs_portal/search/views/v1/experiment.py
- cegs_portal/static/css/project.css
Options are for the ability to select different analysis versions for an experiment
> added analysis selection options

- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
- cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects_table.html
- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
- cegs_portal/search/templates/search/v1/partials/_reg_effect.html
- cegs_portal/search/templates/search/v1/partials/_sig_reg_effects_table.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/templates/search/v1/reg_effect.html
- cegs_portal/search/views/v1/tests/test_search.py
After talking with Alex, "Corrected p-value" is a clearer and more accurate header.
> Change "Significance" to "Corrected p-value"

- cegs_portal/search/templates/search/v1/partials/_sig_reg_effects_table.html
- cegs_portal/search/views/v1/tests/test_search.py
> Edit text search results page

- cegs_portal/search/templates/search/v1/experiments.html
> Updated styling for consistency

- package-lock.json
- requirements/local.txt
Also adds a new local requirement which you sometimes need when testing.
> Bump pytest and caniuse versions

- cegs_portal/search/static/search/js/exp_viz/combo_viz.js
This was already changed in exp_viz.
> Change where combo viz gets genome data from

- requirements/base.txt
- requirements/local.txt
> Bumps dependency versions to get security fixes

- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/experiments.html
- cegs_portal/search/templates/search/v1/partials/_multi_experiment_index.html
- cegs_portal/static/css/project.css
> Combined mult-experiment feat and added styling

- cegs_portal/search/templates/search/v1/experiment_list.html
> Accordion added to filter facets selection

- cegs_portal/search/templates/search/v1/search_results.html
> Corrected accordion arrow direction

- cegs_portal/search/static/search/js/experiment_list/drag_drop.js
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/partials/_multi_experiment_index.html
- cegs_portal/static/css/project.css
> Add select all functionality for experiment index page

- cegs_portal/search/templates/search/index.html
- cegs_portal/templates/base.html
> Responsive index page search header

- cegs_portal/templates/base.html
> Created links and responsive space between images

- cegs_portal/search/views/v1/tests/test_experiment.py
- cegs_portal/search/views/v1/tests/test_experiment_list.py
Splits experiment list view tests from experiment view.
> Speeds up experiment tests, splits into two files

- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/experiments.html
- cegs_portal/search/templates/search/v1/partials/_multi_experiment_index.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
> Multi exp page responsive design

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/partials/_features.html
- cegs_portal/search/templates/search/v1/partials/_reg_effect.html
- cegs_portal/search/templates/search/v1/partials/_target_reg_effect.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/templates/search/v1/target_reg_effects.html
- cegs_portal/static/css/project.css
> responsive dna feature page

- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
This is the last table that needed to have responsive capabilities on the dna feature page
> Responsive proximal table

- cegs_portal/search/templates/search/v1/experiments.html
Multi Experiments Page: After the initial opening of the modal, subsequent attempts didn’t work. Now, the user can reopen the modal successfully on subsequent attempts
> Fix modal display

- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/partials/_experiment_index.html
> Responsive experiment page modal

- cegs_portal/search/static/search/js/genoverse.js
In the browser, when a gene is shown at "see exons" zoom level all returned exons were being used to draw the gene. This was causing extra lines to be shown because there were a lot "different" exons that covered the same locations.
These changes update the code to merge all overlapping exons for a gene into a single exon. The resulting gene drawing looks much better.
This also fixes an issue where the start/end values of the very first transcript were used for the gene. Sometimes that transcript doesn't cover all possible transcripts so the "mouseover" area was wrong and Genoverse would draw other genes over the gene.
Before:
After:
> Merge exons in genoverse

- cegs_portal/uploads/data_loading/analysis.py
- cegs_portal/uploads/data_loading/experiment.py
- cegs_portal/uploads/data_loading/types.py
- cegs_portal/uploads/views/tests/test_experiment_saving.py
We're going to require that locations are 0-indexed, half-open rather than let users decide on their own.
This will be documented in the help.
> Remove "bounds" from upload code

- cegs_portal/search/templates/search/v1/facets.html
- cegs_portal/search/urls.py
- cegs_portal/search/views/v1/__init__.py
- cegs_portal/search/views/v1/facets.py
- cegs_portal/search/views/v1/search.py
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
- cegs_portal/templates/base.html
- cegs_portal/templates/pages/help/data_metadata.html
- cegs_portal/templates/pages/help/data_prep.html
- cegs_portal/templates/pages/help/help.html
- cegs_portal/templates/pages/help/index.html
- config/urls.py
Add some hopefully helpful information for Portal users. This is meant to be a starting point for the help system, not an end point.
> Add Help menu/pages

- cegs_portal/users/forms.py
- requirements/base.txt
Django made a change to the fields in the UserCreationForm
so now we need to use the AdminUserCreationForm
See
https://code.djangoproject.com/ticket/35678
https://github.com/django/django/pull/18484
> Update django and gunicorn, update admin user form

- cegs_portal/search/view_models/v1/search.py
CRE is a new kind of experiment source.
> Add CRE to EXPERIMENT_SOURCES

- cegs_portal/search/static/search/js/exp_viz/chromosomeSvg.js
Previously the "focused" buckets got colored bored. This changes the mechanism so the un-focused buckets get de-saturated and fade out. The focused buckets stay the same.
The changes are faded in and out, which is more pleasant than an abrupt change to saturated/desaturated.
> Change how "focused" buckets are highlighted

- cegs_portal/search/static/search/js/genoverse.js
These names are hopefully clearer about what the tracks are showing
New:
Old:
> Renames genoverse tracks

- compose/local/django/Dockerfile
- compose/local/docs/Dockerfile
- compose/production/django/Dockerfile
- compose/production/django/entrypoint
in particular, updates the production docker entrypoint script.
> Remove remaining psycopg2 references

- cegs_portal/search/static/search/js/genoverse.js
- compose/local/django/Dockerfile
- compose/local/docs/Dockerfile
- compose/production/django/Dockerfile
- compose/production/django/entrypoint
* remove psycopg2 reference from docker entrypoint script
> Prod push 2024/10/18 #2

- config/settings/production.py
* Disable persistent connections
> Prod push 2024/10/23

- cegs_portal/search/static/search/js/exp_viz/render.js
I think this was a copy/paste error from a change from a month ago.
> Change sourceCountRange to targetCountRange

- cegs_portal/search/conftest.py
- cegs_portal/search/static/search/js/genoverse.js
- cegs_portal/search/static/search/js/test/test_genoverse_standin.py
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/view_models/v1/dna_features.py
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/uploads/data_loading/analysis.py
- cegs_portal/uploads/views/tests/conftest.py
- cegs_portal/uploads/views/tests/experiment.json
Splits the "Significant Tested Elements" track into three different tracks, one for each Functional Characterization modality (Reporter Assay, CRISPRi, CRISPRa)
> Three genoverse tracks

- cegs_portal/search/static/search/js/exp_viz/combo_viz.js
Previously the facets were getting intersected, which could make it impossible to filter on certain facet values. For instance, if one experiment had "depleted", "enriched", and "non-sig" REOs and another only had enriched, then the only "Direction" facet value shown would be "enriched". I think union-ing solves the problem and is appropriate for the cases when the experiments are both interesected and unioned together.
Before:
After:
> Union facets on experiment cov page

- cegs_portal/search/static/search/js/dna_feature/closest_feat_type.js
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/partials/_closest_features.html
- cegs_portal/search/urls.py
- cegs_portal/search/view_models/v1/dna_features.py
- cegs_portal/search/views/v1/__init__.py
- cegs_portal/search/views/v1/dna_features.py
- cegs_portal/search/views/v1/tests/conftest.py
- cegs_portal/search/views/v1/tests/test_dna_features.py
We don't include gene/exon/transcript in the filter because those don't have "closest genes" since they are (part of) genes.
> Filter "closest DNA Features" by feature type

- cegs_portal/search/conftest.py
- cegs_portal/search/json_templates/v1/dna_features.py
- cegs_portal/search/models/tests/dna_feature_factory.py
- cegs_portal/search/static/search/js/genoverse.js
- cegs_portal/search/static/search/js/test/test_genoverse_standin.py
- cegs_portal/search/templates/search/v1/dna_feature.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/view_models/v1/dna_features.py
- cegs_portal/search/views/v1/dna_features.py
Adds Enhancer / Promoter, Repressor, and Squelcher tracks
> Add enhancer/promoter, repressor, and squelcher tracks 

- compose/local/django/Dockerfile
- compose/production/django/Dockerfile
- requirements/base.txt
These newer versions contain security fixes.
> Django and python version bumps

- cegs_portal/get_expr_data/view_models.py
- cegs_portal/get_expr_data/views.py
- cegs_portal/search/conftest.py
- cegs_portal/search/json_templates/v1/experiment.py
- cegs_portal/search/json_templates/v1/tests/test_experiment.py
- cegs_portal/search/static/search/js/experiment_list/download_data.js
- cegs_portal/search/static/search/js/experiment_list/drag_drop.js
- cegs_portal/search/static/search/js/experiment_list/facet_filter.js
- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/experiment_list.html
- cegs_portal/search/templates/search/v1/experiments.html
- cegs_portal/search/templates/search/v1/partials/_experiment_collection_list.html
- cegs_portal/search/templates/search/v1/search_results.html
- cegs_portal/search/view_models/v1/experiment.py
- cegs_portal/search/views/v1/experiment.py
- cegs_portal/search/views/v1/tests/test_experiment_list.py
- cegs_portal/static/css/project.css
- cegs_portal/static/css/project.css.tw
Adds a new "experiment collections" tab that includes a facet block,  multi-experiment-selection, and data download section.
Collections work with the multi-experiment collection -- the collection gets converted into its individual experiments.
> Experiment collection UI

- config/settings/local.py
- config/settings/production.py
- config/settings/qa.py
We're seeing DB connection issues in prod. I'm setting QA to use pooled connections and turning on logging for all environments in case we see this again, anywhere. Hopefully this will capture some helpful info for diagnosing the issue.
> Turn on connection pool logging and checks

- cegs_portal/search/templates/search/v1/experiment.html
- cegs_portal/search/templates/search/v1/experiments.html
- cegs_portal/search/templates/search/v1/partials/_multi_experiments_help.html
- cegs_portal/search/urls.py
- cegs_portal/search/views/__init__.py
- cegs_portal/search/views/index.py
> Adding help modal for multi_exp_page

- cegs_portal/igvf/templates/coverage.html
- cegs_portal/igvf/view_models.py
- cegs_portal/igvf/views.py
This allows users to get at the "raw" data
> Add source URL information to IGVF experiment
